fix: improve Ubuntu LTS provisioning support

diff --git a/xCAT-server/share/xcat/netboot/ubuntu/genimage b/xCAT-server/share/xcat/netboot/ubuntu/genimage
--- a/xCAT-server/share/xcat/netboot/ubuntu/genimage
+++ b/xCAT-server/share/xcat/netboot/ubuntu/genimage
@@ -357,7 +357,7 @@ unless ($onlyinitrd) {
     open($aptconfig, ">", "$rootimg_dir/etc/apt/sources.list");
 
     if ($srcdir) {
-        print $aptconfig "deb http://$masternode:$httpport$srcdir $dist main\n";
+        print $aptconfig "deb http://$masternode:$httpport$srcdir $dist main restricted universe\n";
     }
 
     foreach (@pkgdir_internet) {
@@ -369,9 +369,19 @@ unless ($onlyinitrd) {
 
     close($aptconfig);
 
+    # Prevent package maintainer scripts from starting services while the
+    # image root is mounted as a chroot.
+    fake_policy_rc_d();
+
+    $rc = system("$aptgetcmd");
+    if ($rc) {
+        xdie "Failed to update package metadata\n";
+    }
+
     # run apt-get upgrade to update any installed debs
-    my $aptgetcmd_update = $aptgetcmd . "&&" . $aptgetcmdby . " upgrade  ";
-    $rc = system("$aptgetcmd_update");
+    if (!$noupdate) {
+        $rc = system("$aptgetcmdby upgrade");
+    }
 
     # Start to install pkgs in pkglist
     unless ($imagename) {
@@ -463,6 +473,9 @@ unless ($onlyinitrd) {
             }
             my $aptgetcmd_install = $aptgetcmdby . " install --no-install-recommends " . $kernelimage;
             $rc = system("$aptgetcmd_install");
+            if ($rc) {
+                xdie "Failed to install kernel package $kernelimage\n";
+            }
         }
     }
 
@@ -713,7 +726,9 @@ my @moddeps   = <$moddeps>;
 my @checkdeps = @ndrivers;
 while (scalar @checkdeps) {
     my $driver = pop @checkdeps;
-    my @lines = grep /\/$driver:/, @moddeps;
+    my $driver_match = quotemeta($driver);
+    $driver_match =~ s/\\\.ko$/\\.ko(?:\\.(?:gz|xz|zst))?/;
+    my @lines = grep /\/$driver_match:/, @moddeps;
     foreach (@lines) {
         chomp;
         s/.*://;
@@ -722,6 +737,7 @@ while (scalar @checkdeps) {
         my $dep;
         foreach $dep (@deps) {
             $dep =~ s/.*\///;
+            $dep =~ s/\.(?:gz|xz|zst)$//;
             unless (grep { $_ eq $dep } @ndrivers) {    #only add if not added
                 unshift(@checkdeps, $dep);    #recursively check dependencies
                 unshift(@ndrivers,  $dep);
@@ -731,18 +747,12 @@ while (scalar @checkdeps) {
     }
 }
 close($moddeps);
-if (-d "$rootimg_dir/usr/share/dracut") {
+if (-d "$rootimg_dir/usr/share/dracut" or -d "$rootimg_dir/usr/lib/dracut") {
     $dracutmode = 1;
 
-    # get dracut version
-    my $dracutver = `chroot $rootimg_dir dpkg-query  -W dracut | awk '{print \$2}'| aek -F- {print \$1}'`;
-    if ($dracutver =~ /^\d\d\d$/) {
-        if ($dracutver >= "009") {
-            $dracutdir = "dracut_009";
-        } else {
-            $dracutdir = "dracut";    # The default directory
-        }
-    }
+    my $dracutver = `chroot $rootimg_dir dpkg-query -W dracut 2>/dev/null | awk '{print \$2}'`;
+    chomp($dracutver);
+    $dracutdir = "dracut";
     print "Enter the dracut mode. Dracut version: $dracutver. Dracut directory: $dracutdir.\n";
 }
 
@@ -896,7 +906,7 @@ sub getlibs {
     foreach (@libs) {
 	# vdso is a shared library that's embedded in the kernel 
 	# automatically loaded whenever a new process is exec-ed
-	if ( $_ =~ /linux-vdso64/ ) {
+	if ( $_ =~ /linux-vdso/ ) {
 	    next;
 	}
         if (/statically linked/ or /not a dynamic executable/) {
@@ -922,12 +932,22 @@ sub getlibs {
 
 sub mkinitrd_dracut {
     my ($mode) = @_;    # the mode is for statelite or stateless
-    my $dracutmpath = "$rootimg_dir/usr/share/dracut/modules.d/97xcat";
+    my $dracutmpath;
+    if (-d "$rootimg_dir/usr/lib/dracut/modules.d") {
+        $dracutmpath = "$rootimg_dir/usr/lib/dracut/modules.d/97xcat";
+    } else {
+        $dracutmpath = "$rootimg_dir/usr/share/dracut/modules.d/97xcat";
+    }
     mkpath($dracutmpath);
 
     my $perm = (stat("$fullpath/$dracutdir/check"))[2];
     cp("$fullpath/$dracutdir/check", $dracutmpath);
     chmod($perm & 07777, "$dracutmpath/check");
+    if (-f "$fullpath/$dracutdir/module-setup.sh") {
+        $perm = (stat("$fullpath/$dracutdir/module-setup.sh"))[2];
+        cp("$fullpath/$dracutdir/module-setup.sh", $dracutmpath);
+        chmod($perm & 07777, "$dracutmpath/module-setup.sh");
+    }
 
     foreach (@ndrivers) { s/\.ko$//; }
 
@@ -945,9 +965,13 @@ sub mkinitrd_dracut {
         $perm = (stat("$fullpath/$dracutdir/xcat-prepivot.sh"))[2];
         chmod($perm & 07777, "$dracutmpath/xcat-prepivot.sh");
 
-        # update etc/dracut.conf
+        # update etc/dracut.conf - use network-legacy if 40network requires wicked
+        my $netmod = "network";
+        if (-d "$dracutmpath/../35network-legacy" && ! -x "$rootimg_dir/usr/sbin/wicked") {
+            $netmod = "network-legacy";
+        }
         open($DRACUTCONF, '>', "$rootimg_dir/etc/dracut.conf");
-        print $DRACUTCONF qq{dracutmodules+=" xcat nfs base network kernel-modules "\n};
+        print $DRACUTCONF qq{dracutmodules+=" xcat nfs base $netmod kernel-modules "\n};
         print $DRACUTCONF qq{add_drivers+=" $add_drivers "\n};
         print $DRACUTCONF qq{filesystems+=" nfs "\n};
         close $DRACUTCONF;
@@ -975,9 +999,13 @@ sub mkinitrd_dracut {
         $perm = (stat("$fullpath/$dracutdir/installkernel"))[2];
         chmod($perm & 07777, "$dracutmpath/installkernel");
 
-        # update etc/dracut.conf
+        # update etc/dracut.conf - use network-legacy if 40network requires wicked
+        my $netmod = "network";
+        if (-d "$dracutmpath/../35network-legacy" && ! -x "$rootimg_dir/usr/sbin/wicked") {
+            $netmod = "network-legacy";
+        }
         open($DRACUTCONF, '>', "$rootimg_dir/etc/dracut.conf");
-        print $DRACUTCONF qq{dracutmodules+=" xcat nfs base network kernel-modules "\n};
+        print $DRACUTCONF qq{dracutmodules+=" xcat nfs base $netmod kernel-modules "\n};
         print $DRACUTCONF qq{add_drivers+=" $add_drivers "\n};
         close $DRACUTCONF;
     } else {
@@ -1152,7 +1180,7 @@ EOS1
     #print $inifile "mknod /dev/hvc7 c 229 7\n";
 
     foreach (@ndrivers) {
-        print $inifile "insmod /lib/$_\n";
+        print $inifile "[ -f /lib/$_ ] && insmod /lib/$_\n";
     }
 
 
@@ -1188,13 +1216,24 @@ PRINIC=$prinic
 NODESTATUS='y'
 XCATIPORT="3002"
 
+iface_exists() {
+    [ -n "\$1" ] && [ -d "/sys/class/net/\$1" ]
+}
+
 for i in `cat /proc/cmdline`; do
     KEY=`echo \$i |awk -F= '{print \$1}'`
     if [ "\$KEY" == 'netdev' ]; then
         NETDEV=`echo \$i |awk -F= '{print \$2}'`
     elif [ "\$KEY" == 'BOOTIF' ]; then
-        VALUE=`echo \$i |awk -F= '{print \$2}'|sed -e s/^01-// -e s/-/:/g`
-        BOOTIF=`ifconfig -a|grep -i "hwaddr \$VALUE"|awk '{print \$1}'`
+        VALUE=`echo \$i |awk -F= '{print \$2}'|sed -e s/^01-// -e s/-/:/g|tr 'A-Z' 'a-z'`
+        for devpath in /sys/class/net/*; do
+            [ -e "\$devpath/address" ] || continue
+            if [ "\`cat \$devpath/address\`" = "\$VALUE" ]; then
+                BOOTIF=\${devpath##*/}
+                break
+            fi
+        done
+        [ -z "\$BOOTIF" ] && BOOTIF=`ifconfig -a|grep -i "hwaddr \$VALUE"|awk '{print \$1}'`
     elif [ "\$KEY" == 'XCAT' ]; then
         VALUE=`echo \$i |awk -F= '{print \$2}'`
         # format: XCAT=xcatmaster:3001
@@ -1215,16 +1254,23 @@ for i in `cat /proc/cmdline`; do
 done
 
 if [ -z "\$IFACE" ]; then
-    if [ ! -z "\$NETDEV" ]; then
-        IFACE=\$NETDEV
-    elif [ ! -z "\$BOOTIF" ]; then
+    if iface_exists "\$BOOTIF"; then
         IFACE=\$BOOTIF
-    elif [ ! -z "\$PRINIC" ]; then
+    elif iface_exists "\$NETDEV"; then
+        IFACE=\$NETDEV
+    elif iface_exists "\$PRINIC"; then
         IFACE=\$PRINIC
     else
-        echo "\${RED}Couldn't find the proper booting device, switch to shell...\${RESET}"
-        shell
-        exit
+        for devpath in /sys/class/net/*; do
+            IFACE=\${devpath##*/}
+            [ "\$IFACE" != "lo" ] && break
+            IFACE=
+        done
+        if [ -z "\$IFACE" ]; then
+            echo "\${RED}Couldn't find the proper booting device, switch to shell...\${RESET}"
+            shell
+            exit
+        fi
     fi
 fi
 
@@ -1666,9 +1712,10 @@ EOMS
     }
 
     # add extra commands for initrd
-    foreach ("usr/bin/dig", "bin/busybox", "bin/bash", "sbin/mount.nfs", "usr/bin/rsync", "sbin/insmod", "sbin/udevadm", "sbin/modprobe", "sbin/blkid", "sbin/depmod", "usr/bin/wget", "usr/bin/xz", "bin/gzip", "bin/tar") {
-        getlibs($_);
-        push @filestoadd, $_;
+    foreach my $dest ("usr/bin/dig", "bin/busybox", "bin/bash", "sbin/mount.nfs", "usr/bin/rsync", "sbin/insmod", "sbin/udevadm", "sbin/modprobe", "sbin/blkid", "sbin/depmod", "usr/bin/wget", "usr/bin/xz", "bin/gzip", "bin/tar") {
+        my $src = find_rootimg_file($dest);
+        getlibs($src);
+        push @filestoadd, [ $src, $dest ];
     }
 
     # Workaround for Ubuntu 18.04 busybox bug
@@ -1691,16 +1738,16 @@ EOMS
 
 
     if ($arch =~ /x86_64/) {
-        push @filestoadd, "lib64/libnss_dns.so.2";
-        #the path of libnss_dns.so.2 for ubuntu 14.4+
-        push @filestoadd, "lib/x86_64-linux-gnu/libnss_dns.so.2";
-        push @filestoadd, "lib64/libresolv.so.2";
+        foreach ("lib64/libnss_dns.so.2", "lib/x86_64-linux-gnu/libnss_dns.so.2", "lib64/libresolv.so.2") {
+            push @filestoadd, $_ if (-e "$rootimg_dir/$_");
+        }
     } elsif ($arch =~ /ppc64el/) {
-        push @filestoadd, "lib/powerpc64le-linux-gnu/libnss_files.so.2";
-        push @filestoadd, "lib/powerpc64le-linux-gnu/libnss_dns.so.2";
+        foreach ("lib/powerpc64le-linux-gnu/libnss_files.so.2", "lib/powerpc64le-linux-gnu/libnss_dns.so.2") {
+            push @filestoadd, $_ if (-e "$rootimg_dir/$_");
+        }
 
     } else {
-        push @filestoadd, "lib/libnss_dns.so.2";
+        push @filestoadd, "lib/libnss_dns.so.2" if (-e "$rootimg_dir/lib/libnss_dns.so.2");
     }
     push @filestoadd, keys %libhash;
 
@@ -1716,9 +1763,7 @@ EOMS
             } elsif (-f "$pathtofiles/" . $_->[0]) {
                 $srcpath = "$pathtofiles/" . $_->[0];
             }
-            mkpath(dirname("/tmp/xcatinitrd.$$/" . $_->[1]));
-            copy($srcpath, "/tmp/xcatinitrd.$$/" . $_->[1]);
-            chmod 0755, "/tmp/xcatinitrd.$$/" . $_->[1];
+            copy_initrd_file($srcpath, "/tmp/xcatinitrd.$$/" . $_->[1]);
         } else {
 
             #print "$_\n";
@@ -1728,9 +1773,7 @@ EOMS
             } elsif (-f "$pathtofiles/$_") {
                 $srcpath = "$pathtofiles/$_";
             }
-            mkpath(dirname("/tmp/xcatinitrd.$$/$_"));
-            copy("$srcpath", "/tmp/xcatinitrd.$$/$_");
-            chmod 0755, "/tmp/xcatinitrd.$$/" . $_;
+            copy_initrd_file($srcpath, "/tmp/xcatinitrd.$$/$_");
         }
     }
 
@@ -1743,7 +1786,7 @@ EOMS
         system("cp  $rootimg_dir/lib/modules/$kernelver/modules.order /tmp/xcatinitrd.$$/lib/modules/$kernelver/modules.order");
     }
 
-    system("chroot /tmp/xcatinitrd.$$/ depmod $kernelver");
+    system("chroot /tmp/xcatinitrd.$$/ /sbin/depmod $kernelver");
 
     # Copy udev and network scripts into initrd for s390x, which also works for other platforms
     # udev
@@ -1789,12 +1832,49 @@ sub isaptdir {
 
 sub isnetdriver {
     foreach (@ndrivers) {
-        if ($File::Find::name =~ /\/$_/) {
+        my $driver_match = quotemeta($_);
+        $driver_match =~ s/\\\.ko$/\\.ko(?:\\.(?:gz|xz|zst))?/;
+        if ($File::Find::name =~ /\/$driver_match$/) {
             my $filetoadd = $File::Find::name;
             $filetoadd =~ s!$rootimg_dir/!!;
             push @filestoadd, [ $filetoadd, "lib/$_" ];
         }
     }
+}
+
+sub find_rootimg_file {
+    my ($file) = @_;
+
+    return $file if (-e "$rootimg_dir/$file");
+
+    my $base = basename($file);
+    foreach my $candidate ("usr/bin/$base", "bin/$base", "usr/sbin/$base", "sbin/$base") {
+        return $candidate if (-e "$rootimg_dir/$candidate");
+    }
+
+    xdie "Failed to find $file in $rootimg_dir\n";
+}
+
+sub copy_initrd_file {
+    my ( $src, $dest ) = @_;
+
+    mkpath(dirname($dest));
+    if ( $src =~ /\.ko\.(gz|xz|zst)$/ ) {
+        my %decompressor = (
+            gz  => [ 'gzip', '-dc' ],
+            xz  => [ 'xz',   '-dc' ],
+            zst => [ 'zstd', '-dc' ],
+        );
+        my @cmd = ( @{ $decompressor{$1} }, $src );
+        open( my $in, '-|', @cmd ) || xdie "Failed to decompress $src\n";
+        open( my $out, '>', $dest ) || xdie "Failed to open $dest\n";
+        copy( $in, $out ) || xdie "Failed to copy $src to $dest\n";
+        close($out);
+        close($in) || xdie "Failed to decompress $src\n";
+    } else {
+        copy( $src, $dest ) || xdie "Failed to copy $src to $dest\n";
+    }
+    chmod 0755, $dest;
 }
 
 sub postscripts {
@@ -2187,5 +2267,3 @@ sub usage {
 
     return 0;
 }
-
-
